# Generated by Django 3.2.3 on 2021-06-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochetApp', '0002_alter_profile_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='totalPrice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='itemPrice',
            field=models.IntegerField(),
        ),
    ]
