# Generated by Django 3.2.5 on 2021-07-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochetApp', '0006_product_itemform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='itemsOrdered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='order',
            name='totalPrice',
        ),
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.FileField(default='null', upload_to='invoices'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ManyToManyField(related_name='orders', to='crochetApp.User'),
        ),
    ]
