# Generated by Django 3.2.3 on 2021-06-01 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='poster',
            new_name='author',
        ),
    ]
