# Generated by Django 3.2.3 on 2021-06-10 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_auto_20210609_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profImag', to='shopApp.user')),
            ],
        ),
    ]
