# Generated by Django 3.2.3 on 2021-06-02 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_rename_poster_reply_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='itemPrice',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shopApp.user')),
                ('itemsOrdered', models.ManyToManyField(related_name='items', to='shopApp.Product')),
            ],
        ),
    ]
