# Generated by Django 3.2.3 on 2021-06-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0004_auto_20210602_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='itemCount',
        ),
    ]
